export const routeMap = {
  student: {
    시간표: "/student/timetable",
    "출석 관리": "/student/attendance",
    "강의 계획서 조회": "/student/syllabus",
    "강의 종합": "/lectureroom/0",
    "수강/성적 조회": "/student/grade",
    "석차 조회": "/student/rank",
    "휴복학 신청": "/student/leave/request",
    "대시 보드": "/student/dashboard",
    "내 정보 확인": "/my/:userId",
    "수강 신청": "/student/sugang",
    "개인정보 수정": "/my/:userId/editinfo",
    "비밀번호 변경": "/my/:userId/editpassword",
  },
  faculty: {
    "강의 종합": "/lectureroom/:lectureId",
    "출석 관리": "/professor/attendance",
    "강의 계획서 작성": "/professor/syllabus",
    "성적 처리": "/professor/grade/input",
    "내 정보 확인": "/my/:userId",
    "개인정보 수정": "/my/:userId/editinfo",
    "비밀번호 변경": "/my/:userId/editpassword",
  },
  staff: {
    "학적 관리": "/staff/leave/approval",
    "구성원 추가": "/staff/management/add",
    "구성원 삭제": "/staff/management/delete",
    "내 정보 확인": "/my/:userId",
    "개인정보 수정": "/my/:userId/editinfo",
    "비밀번호 변경": "/my/:userId/editpassword",
  },
};
