export const routeMap = {
  student: {
    시간표: "/timetable",
    "출석 관리": "/attendance/student",
    "강의 계획서 조회": "/syllabus/student",
    "수강/성적 조회": "/student/grade",
    "석차 조회": "/student/rank",
    "휴복학 신청": "/leave-request",
    "강의 종합": "/lectureroom/0",
    "온라인 강의 콘텐츠 시청": "",
    공지사항: "/notice",
    "강의 자료실": "",
    "과제 제출": "/assignment",
    "대시 보드": "/student/dashboard",
    "마이 페이지": "/my",
    "수강 신청": "/student/sugang",
  },
  faculty: {
    "출석 관리": "/attendance/professor",
    "강의 계획서 작성": "/syllabus/professor",
    "성적 입력": "/gradeInput",
    "온라인 강의 콘텐츠 업로드": "",
    "공지사항 업로드": "",
    "자료실 업로드": "",
    "제출된 과제 확인": "",
    "마이 페이지": "/my",
  },
  staff: {
    "학적 관리": "/leave-approval",
    "구성원 관리": "staff/management",
    "마이 페이지": "/my",
  },
};
